"""Calendar risk-event endpoints.

Prefix: ``/api/calendar``

Routes
──────
GET    /          → list events  (query: ``port_id``, ``event_type``)
POST   /          → create event
DELETE /{event_id} → delete event
POST   /sync      → trigger provider sync (holidays, weather, risk zones)
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependency import get_db
from app.schemas.calender import (
    CalendarEventSchema,
    EventCreateSchema,
    SyncResultSchema,
)
from app.services.calender import (
    add_event,
    list_events,
    remove_event,
    sync_external_events,
)
from app.config import settings

router = APIRouter(tags=["calendar"])


# ── GET /api/calendar ───────────────────────────────────────────────────────
@router.get("/", response_model=list[CalendarEventSchema])
async def get_calendar_events(
    port_id: str | None = Query(None, description="Filter by port id"),
    event_type: str | None = Query(None, description="Filter by event type"),
    db: AsyncSession = Depends(get_db),
):
    """Return all calendar events, with optional port / type filters.

    On first call with an empty DB, mock data is seeded automatically
    when ``DATA_MODE=mock``.
    """
    # # Auto-seed mock data when DB is empty and mode is mock.
    # if settings.DATA_MODE == "mock":
    #     await seed_mock_data(db)

    events = await list_events(db, port_id=port_id, event_type=event_type)
    return [CalendarEventSchema.model_validate(e) for e in events]


# ── POST /api/calendar ─────────────────────────────────────────────────────
@router.post("/", response_model=CalendarEventSchema, status_code=201)
async def create_calendar_event(
    body: EventCreateSchema,
    db: AsyncSession = Depends(get_db),
):
    """Create a new calendar event (user-submitted)."""
    db_dict = body.to_db_dict(event_id="")  # id will be generated by service
    event = await add_event(db, db_dict)
    return CalendarEventSchema.model_validate(event)


# ── DELETE /api/calendar/{event_id} ─────────────────────────────────────────
@router.delete("/{event_id}", status_code=204)
async def delete_calendar_event(
    event_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Delete a calendar event by id."""
    deleted = await remove_event(db, event_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Event not found")
    return None


# ── POST /api/calendar/sync ────────────────────────────────────────────────
@router.post("/sync", response_model=SyncResultSchema)
async def sync_events(
    db: AsyncSession = Depends(get_db),
):
    """Trigger a full sync from external providers.

    Fetches holidays (Nager.Date), weather (Open-Meteo), and risk zones,
    then upserts everything into the database.
    """
    count = await sync_external_events(db)
    return SyncResultSchema(
        synced=count,
        message=f"Successfully synced {count} events from external providers.",
    )
